version: '3'

services:
  immport-cralwer:
    build:
      context: immport_crawler
      dockerfile: Dockerfile
    volumes:
      - data:/data
#  zenodo-crawler:
#    build:
#      context: zenodo_crawler
#      dockerfile: Dockerfile
#    volumes:
#      - crawler-data:/data/crawler-data
  mongodb:
    image: mongo:4.4
    ports:
      - "127.0.0.1:27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  nde-hub:
    build:
      context: biothings-hub
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.8
    depends_on:
      - "mongodb"
      - "elasticsearch"
    environment:
      - ES_HOST=elasticsearch:9200
      - MONGO_HOST=mongodb:27017
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - data:/data
    ports:
      - "127.0.0.1:7022:7022"
      - "127.0.0.1:7080:7080"
  hub-webapp:
    build:
      context: biothings-webapp
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
volumes:
  data:
