version: '3'

services:
  # when updating changes to code: "docker-compose up --detach --build nde-hub"
  ncbi_geo-crawler:
    build:
      context: ncbi_geo_crawler
      dockerfile: Dockerfile
      # uncomment to run development crontab
      args:
        CRONTAB: dev-crontab
    volumes:
      - data:/data
      - cache:/cache
  omicsdi-crawler:
    build:
      context: omicsdi_crawler
      dockerfile: Dockerfile
      # uncomment to run development crontab
      args:
        CRONTAB: dev-crontab
    volumes:
      - data:/data
      - cache:/cache
  mongodb:
    image: mongo:5.0
    ports:
      - "127.0.0.1:27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
  # socat is used to expose the docker socket from local to the hub container
  # Container has no permission to access local docker socket so we need to create a tcp port to expose it
  # https://forums.docker.com/t/mounting-using-var-run-docker-sock-in-a-container-not-running-as-root/34390/7
  socat:
    image: alpine/socat
    # command: tcp-listen:2375,fork,reuseaddr,keepalive=1,keepidle=60,keepintvl=10,keepcnt=3 unix-connect:/var/run/docker.sock
    command: tcp4-listen:2375,fork,reuseaddr unix-client:/var/run/docker.sock
    user: root
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "2375:2375"
  nde-hub:
    build:
      context: biothings-hub
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
    # May need to configure this if you get timeout errors after 2 hours. 
    # sysctls:
    #   net.ipv4.tcp_keepalive_intvl: '45'
    #   net.ipv4.tcp_keepalive_probes: '15'
    #   net.ipv4.tcp_keepalive_time: '7200'
    # privileged: true
    depends_on:
      - "mongodb"
      - "elasticsearch"
      - "socat"
    environment:
      - ES_HOST=elasticsearch:9200
      - MONGO_HOST=mongodb:27017
      - DOCKER_HOST=socat:2375
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - data:/data
      - cache:/cache
    ports:
      # ports are mapped to 19522 and 19580 because of changes for production environment
      - "127.0.0.1:7022:19522"
      - "127.0.0.1:7080:19580"
      - "127.0.0.1:7081:19581"
  hub-webapp:
    build:
      context: biothings-webapp
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nde/data
  cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nde/cache
