version: '3'

services:
  # when updating changes to code: "docker-compose up --detach --build immport-crawler"
  immport-crawler:
    build:
      context: immport_crawler
      dockerfile: Dockerfile
      # uncomment to run development crontab
      # args:
      #   CRONTAB: dev-crontab
    volumes:
      - data:/data
  zenodo-crawler:
    build:
      context: zenodo_crawler
      dockerfile: Dockerfile
      # uncomment to run development crontab
      # args:
      #   CRONTAB: dev-crontab
    volumes:
      - data:/data
  niaid-crawler:
    build:
      context: niaid_crawler
      dockerfile: Dockerfile
      # uncomment to run development crontab
      # args:
      #   CRONTAB: dev-crontab
    volumes:
      - data:/data
  omicsdi_crawler:
    build:
      context: omicsdi_crawler
      dockerfile: Dockerfile
      # uncomment to run development crontab
      # args:
      #   CRONTAB: dev-crontab
    volumes:
      - data:/data
  ncbi-geo-crawler:
    build:
      context: ncbi_geo_crawler
      dockerfile: Dockerfile
    # uncomment to run development crontab
      # args:
      #   CRONTAB: dev-crontab
    volumes:
      - data:/data
  mongodb:
    image: mongo:4.4
    ports:
      - "127.0.0.1:27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  nde-hub:
    build:
      context: biothings-hub
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.8
    depends_on:
      - "mongodb"
      - "elasticsearch"
    environment:
      - ES_HOST=elasticsearch:9200
      - MONGO_HOST=mongodb:27017
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - data:/data
    ports:
      # ports are mapped to 19522 and 19580 because of changes for production environment
      - "127.0.0.1:7022:19522"
      - "127.0.0.1:7080:19580"
  hub-webapp:
    build:
      context: biothings-webapp
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nde/data
