name: Source Suggestion
description: Suggest a source for inclusion in the NIAID Discovery Ecosystem
title: "[Source]: "
labels: ["new data source"]

body:
  - type: markdown
    attributes:
      value: |
        Hello! Thank you for your interest in submitting a new source and contributing to our efforts to maximize data discoverability. Please fill out all of the following information and submit so we can evaluate this new source. You will need the name and url of source       
  - type: input
    id: repoName
    attributes:
      label: Source Name
      description: What is the name of the source?
      placeholder: ex. Zenodo
    validations:
      required: True
  - type: input
    id: repoUrl
    attributes:
      label: Source URL
      description: What is the url of the source?
      placeholder: ex. https://zenodo.org/
    validations:
      required: true
  - type: textarea
    id: repoDescription
    attributes:
      label: Source Description
      description: Please provide a description of the source.
      placeholder: ex. Zenodo helps researchers receive credit by making the research results citable and through OpenAIRE integrates them into existing reporting lines to funding agencies like the European Commission. Citation information is also passed to DataCite and onto the scholarly aggregators."
    validations:
      required: true
  - type: dropdown
    id: repoAccess
    attributes:
      label: Source Access
      description: Does this source require a user account login? Y/N
      options:
        - "Yes, account needed"
        - "No access issue, account not needed"
        - "Unknown"
    validations:
      required: true
  - type: textarea
    id: repoFunding
    attributes:
      label: Source Funding
      description: If you know information about the funder behind this source, please share it below
      placeholder: ex. CERN
    validations:
      required: false
  - type: textarea
    id: repoRelevance
    attributes:
      label: Source Relevance
      description: Explain in couple sentences how adding structured metadata to this new source could benefit the biomedical community.
      placeholder: The rationale for including this source is...
    validations:
      required: true
  - type: checkboxes
    id: WBSlink
    attributes:
      label: Related WBS task
      description: Please provide links to any relevant tasks/issues in the WBS/Roadmap repository https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues). 
      options:
        - label: Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
        - label: Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
        - label: Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
    validations:
      required: false       
  - type: markdown
    attributes:
      value: |
        "## Additional Notes for internal use only." 
  - type: markdown
    attributes:
      value: |
        Submitter, ignore everything below this point.
  - type: checkboxes
    id: issueStatus
    attributes:
      label: For internal use only. Assignee, please select the status of this issue
      options:
        - label: Not yet started
        - label: In process
        - label: Blocked
        - label: Will not include
    validations:
      required: false
  - type: textarea
    id: repoStatusDescription
    attributes:
      label: Status Description
      description: If the status of this issue is BLOCKED or WILL NOT INCLUDE, please provide more details.
    validations:
      required: false
  - type: checkboxes
    id: issueTaskList
    attributes:
       label: Source to-do list
       description: For internal use only. Assignee, check off the tasks as you complete them
       options:
         - label: License check- Can this source be included?
         - label: Class check- Does this source have the right class of research output for inclusions?
         - label: NIAID Review- Does NIAID approve of the inclusion of this source?
         - label: Data access check- Have data access issues been resolved?
         - label: Structured data check- Does this source have structured data?
         - label: Mapping check- Has the properties from this source been mapped to the schema?
         - label: Parser check- Has the parser been written?
         - label: Parsed data check- Has a sanity check on the data obtained from this source been performed?
         - label: Merge data- Has the crawler/plugin been successfully integrated with the system?
         - label: Issues could not be resolved - Add as a single record via the DDE
