from hub.dataload.nde import NDESourceUploader
from utils.csv_helper import get_source_data

# Example __metadata__ dictionary:
# <SOURCE_NAME> = https://api.data.niaid.nih.gov/v1/metadata
# __metadata__ = {
# "src_meta": {
# 'description': 'A short description of what the source offers, usually found on the source's about page',
# 'name': 'The full source name, Ex. Mendeley Data (not mendeley)',
# 'identifier':'includedInDataCatalog.name value',
# 'schema': 'A dict where the key is the source's metadata variable and the value is our transformation. Ex: {"summary":"description"},
# 'url': 'The source's URL homepage',
# }
# }


class Biotools_Uploader(NDESourceUploader):
    name = "biotools"
    __metadata__ = {
        "src_meta": {
            "sourceInfo": {
                "description": "Essential scientific and technical information about software tools, databases and services for bioinformatics and the life sciences. bio.tools resource descriptions adhere to rigorous information standards including precise semantics and syntax. Scientific aspects are provided by the EDAM ontology and technical aspects are covered by biotoolsSchema. bio.tools is anchored within ELIXIR, the European Infrastructure for Biological Information. ELIXIR unites Europe's leading life science organisations in managing and safeguarding the increasing volume of data being generated by publicly funded research. It coordinates, integrates and sustains bioinformatics resources across its member states and enables users in academia and industry to access services that are vital for their research.",
                "identifier": "biotools",
                "name": "biotools",
                "schema": get_source_data(name),
                "url": "https://bio.tools/",
            }
        }
    }
